### ISSUE TITLE
ZIP File Issues

### ISSUE THREAD

**Issue by Robby9705** [alexbakker/aegis-simple-icons#1]
Device: Redmi K20 Pro (Android 11)

Issue Description (According To Aegis-Authenticator):  _**com.beemdevelopment.aegis.icons.IconPackException: Java.io.IOException: Unable to find pack.json in the root of the ZIP file**_

Comment: The App Doesn't Regard The ZIP File As Valid, It's Most Probably Something To Do With The pack.json File

**Comment by alexbakker** [comment]
I'm unable to reproduce this issue. Tested with: https://github.com/alexbakker/aegis-simple-icons/releases/download/v47/aegis-simple-icons-v47.zip. Are you sure you're selecting the right file?

**Comment by Robby9705** [comment]
Ah, It Works Now. I Am Really Sorry For The Inconvenience. :D
