### ISSUE TITLE
[request] speedypage.com

### ISSUE THREAD

**Issue by 3xploiton3** [alexbakker/aegis-simple-icons#2]
https://speedypage.com/

<details>
https://pbs.twimg.com/profile_images/1510261768324587534/ZY9QXW2R_400x400.jpg
</details>

![image](https://github.com/alexbakker/aegis-simple-icons/assets/19517680/5dc7afd2-78bd-43c4-9c4c-3756a66f1f0b)

**Comment by alexbakker** [comment]
This repo does not accept requests for new icons.
