### ISSUE TITLE
Razer's logo is not properly aligned in the icon

### ISSUE THREAD

**Issue by DoodleGeist** [alexbakker/aegis-simple-icons#3]
Razer's logo is not centre aligned in the icon pack

Also could you please add icons for Koofr cloud storage, Larian Studios, real-debrid, standard notes, tresorit and the good cloud

Thank you so much for the pack.

**Comment by alexbakker** [comment]
> Razer's logo is not centre aligned in the icon pack

This project automatically generates the icon pack based on [simple icons](https://github.com/simple-icons/simple-icons) and has some very primitive logic that attempts to center the icon. Most icons look alright, some don't. I don't make manual adjustments.

> Also could you please add icons for Koofr cloud storage, Larian Studios, real-debrid, standard notes, tresorit and the good cloud

This project does not accept requests for new icons.
