### ISSUE TITLE
Add icon His Majesty's Revenue and Customs in the United Kingdom

### ISSUE THREAD

**Issue by JJWatMyself** [alexbakker/aegis-simple-icons#5]
His Majesty's Revenue and Customs in the United Kingdom

2FA shows as "Government Gateway" and logo can be seen here:

https://www.gov.uk/government/organisations/hm-revenue-customs

Logo found here:

https://logos-world.net/wp-content/uploads/2021/08/HMRC-Emblem.png

**Comment by alexbakker** [comment]
This repo does not accept requests for new icons.
